FROM debian:buster

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    file \
    lsb-release \
    man \
    python \
    python3 \
    qemu \
    qemu-user-static \
    vim
